### ISSUE TITLE
Teapot doesn't appear when loading the Euler Angles binary file

### ISSUE THREAD

**Issue by acourt** [Motsai/promotion-webapps#1]
Running the latest master branch html and loading the euleranglePackets.bin file doesn't show anything.

![teapotdoesntappear](https://cloud.githubusercontent.com/assets/1243293/11069231/20d1a6aa-87a3-11e5-8dd8-7f12ec3b0e25.png)

**Comment by hyyao** [comment]
It should work better now. Tested with Chrome in windows 10.

**Comment by jsamch** [comment]
Got the teapot to work also.  Earlier version did not show the teapot unless a file was loaded.  Now it starts with a teapot.  Good to check that the WebGL is working.

**Comment by jsamch** [comment]
@acourt Try it again in Linux.  On my Windows 10 it works.

**Comment by acourt** [comment]
Tried it again with the Chrome app editor and it works correctly. What I was doing wrong was to open the "main.html" file in chrome.
